/*
 * This source file was generated by the Gradle 'init' task
 */
package main;

import org.junit.Test;
//import static org.junit.Assert.*;

public class MainTest {
    @Test
    public void test() {
    }
}
