/*
 * This source file was generated by the Gradle 'init' task
 */
package interpreter;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class Interpreter {

    static boolean hadError = false;

    public static void main(String[] args) throws IOException {
        if (args.length > 1) {
            System.out.println("usage: lucas [script]");
            // unix sysexits.h: EX_USAGE 64 - command line usage error
            System.exit(64);
        } else if (args.length == 1) {
            // Run from source file
            runFile(args[0]);
        } else {
            // REPL, read evaluate print loop
            runPrompt();
        }
    }

    private static void runFile(String path) throws IOException {
        byte[] bytes = Files.readAllBytes(Paths.get(path));

        run(new String(bytes, Charset.defaultCharset()));

        if (hadError) {
            // unix sysexits.h: EX_DATAERR 65 - data format error
            System.exit(65);
        }
    }

    private static void run(String source) {
        // not to be confused with java.util.Scanner
        Scanner scanner = new Scanner(source);
        List<Token> tokens = scanner.scanTokens();
        // Just print for now
        for (Token token : tokens) {
            System.out.println(token);
        }
    }

    private static void runPrompt() throws IOException {
        InputStreamReader input = new InputStreamReader(System.in);
        BufferedReader reader = new BufferedReader(input);

        while (true) {
            System.out.println(">");
            String line = reader.readLine();
            if (line == null) {
                break;
            }
            run(line);
            // reset error after each line in REPL to avoid crashing
            hadError = false;
        }
    }

    public static void error(int line, String message) {
        report(line, "", message);
    }

    private static void report(int line, String where, String message) {
        System.err.println("[line " + line + "] Error" + where + ": " + message);
        hadError = true;
    }
}
