/*
 * This source file was generated by the Gradle 'init' task
 */
package interpreter;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test
    public void appHasAGreeting() {
        Lang classUnderTest = new Lang();
        assertNotNull("app should have a greeting", classUnderTest.getClass());
    }
}
